<?php
// Thread keeping track of the whitelisted ranks:
// https://hypixel.net/threads/guild-rank-whitelist.1787255/
return array(
    'whitelist' =>
        array(
            'guild master',
            'guildmaster',
            'founder',
            'co-founder',
            'owner',
            'co-owner',
            'co owner',
            'guild leader',
            'leader',
            'officer',
            'adviser',
            'advisor',
            'veteran',
            'trusted',
            'trusted member',
            'retired',
            'retiree',
            'trial',
            'trial member',
            'elder',
            'trainee',
            'manager',
            'head officer',
            'co-master',
            'sergeant',
            'lieutenant',
            'newbie',
            'elite',
            'senior',
            'senior officer',
            'crew',
            'crew member',
            'trial officer',
            'junior officer',
            'elite member',
            'captain',
            'general',
            'rookie',
            'private',
            'active',
            'active Member',
            'recruiter',
            'initiate',
            'commander'
        )
);