<?php
// Thread keeping track of the whitelisted ranks:
// https://hypixel.net/threads/guild-rank-whitelist.1787255/
return array(
    'whitelist' =>
        array(
            'guild master',
            'guildmaster',
            'master',
            'co-master',
            'founder',
            'co-founder',
            'owner',
            'co-owner',
            'co owner',
            'guild leader',
            'leader',
            'commander',
            'sergeant',
            'lieutenant',
            'manager',
            'management team',
            'events team',
            'council',
            'elder',
            'captain',
            'general',
            'senior',
            'senior officer',
            'head officer',
            'officer',
            'junior officer',
            'trainee officer',
            'trial officer',
            'adviser',
            'advisor',
            'elite',
            'veteran',
            'private',
            'recruiter',
            'trusted',
            'trusted member',
            'elite member',
            'member',
            'active',
            'active member',
            'crew',
            'crew member',
            'trainee',
            'trial',
            'trial member',
            'newbie',
            'initiate',
            'rookie',
            'retired',
            'retiree'
        )
);